# --- Inline keyboard button commands ---
OVERVIEW_DESIGN_COMMAND = 'view_design_command'
ORDER_COMMAND = 'order_command'
TO_FAVORITE_COMMAND = 'save_to_favorite_command'
NEXT_DESIGN_COMMAND = 'next_design_command'
NEXT_COMMAND = 'next_command'
PREV_COMMAND = 'prev_command'
TO_START_COMMAND = 'to_start_command'
DELETE_COMMAND = 'delete_command'
ORDER_DESIGN_COMMAND = 'order_design_command'
NEXT_SCENARIO_COMMAND = 'next_scenario_command'
INSTRUCTION_COMMAND = 'instruction_command'
RETURN_COMMAND = 'return_command'
CONNECT_DESIGNER_COMMAND = 'connect_designer_command'
UPLOAD_NEW_IMAGE_COMMAND = 'upload_new_image_command'
