from .inline_commands import (
    OVERVIEW_DESIGN_COMMAND,
    ORDER_COMMAND,
    TO_FAVORITE_COMMAND,
    NEXT_DESIGN_COMMAND,
    NEXT_COMMAND,
    PREV_COMMAND,
    TO_START_COMMAND,
    DELETE_COMMAND,
    ORDER_DESIGN_COMMAND,
    NEXT_SCENARIO_COMMAND,
    INSTRUCTION_COMMAND,
    RETURN_COMMAND,
    CONNECT_DESIGNER_COMMAND,
    UPLOAD_NEW_IMAGE_COMMAND
)

from .reply_commands import (
    SIMPLE_DESIGN_COMMAND,
    COMPLEX_DESIGN_COMMAND,
    FAVORITE_COMMAND,
    HELP_COMMAND,
    EXAMPLES_COMMAND
)

from .text_commands import (
    STARTUP_TEXT,
    GREETING_USER_TEXT,
    DESIGN_STARTUP_TEXT,
    DESIGN_DESCRIPTION_TEXT,
    HELP_STARTUP_TEXT,
    HELP_WARNING_TEXT,
    HELP_DESCRIPTION_TEXT,
    OVERVIEW_STARTUP_TEXT,
    UPLOAD_PHOTO_TEXT,
    INSTRUCTION_TEXT,
    UPLOAD_PHOTO_TEXT,
    UPLOAD_PHOTO_SUCCESS_TEXT,
    UPLOAD_PHOTO_FINISHED_TEXT,
    ADMIN_AUTH_MESSAGE_TEXT,
    NO_FAVORITE_MESSAGE_TEXT,
    ORDERED_MESSAGE_TEXT,
    NEW_ORDER_MESSAGE_TEXT,
    NEW_ORDER_MESSAGE_WITHOUT_PHOTO_TEXT,
    CONNECT_DESIGNER_MESSAGE_TEXT,
    EXAMPLES_MESSAGE_TEXT,

    INLINE_OVERVIEW_BUTTON_TEXT,
    INLINE_ORDER_BUTTON_TEXT,
    INLINE_TO_FAVORITE_BUTTON_TEXT,
    INLINE_NEXT_DESIGN_BUTTON_TEXT,
    INLINE_NEXT_BUTTON_TEXT,
    INLINE_PREV_BUTTON_TEXT,
    INLINE_TO_START_BUTTON_TEXT,
    INLINE_DELETE_BUTTON_TEXT,
    INLINE_ORDER_DESIGN_BUTTON_TEXT,
    INLINE_NEXT_SCENARIO_BUTTON_TEXT,
    INLINE_INSTRUCTION_BUTTON_TEXT,
    INLINE_RETURN_BUTTON_TEXT,
    INLINE_CONNECT_DESIGNER_BUTTON_TEXT,
    INLINE_UPLOAD_NEW_IMAGE_BUTTON_TEXT,

    TUTORIAL_VIDEO_URL
)
